---
- name: "Require Correct Linux Distribution"
  ansible.builtin.assert:
    that:
      ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('22.0.0', '>=') and
      'microsoft' in ansible_kernel | lower
    msg: "This Linux distribution '{{ ansible_distribution }} {{ ansible_distribution_version }}' is not supported by the role."
    quiet: true
  tags: wsl-keeagent

- name: "Detect WSL version"
  ansible.builtin.set_fact:
    wsl_version: "{{ 'wsl2' if ansible_kernel is search('WSL2') else 'wsl1' }}"
    templates_root: "{{ 'wsl2' if ansible_kernel is search('WSL2') else 'wsl1' }}/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
    files_root: "{{ 'wsl2' if ansible_kernel is search('WSL2') else 'wsl1' }}/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
  tags: wsl-keeagent

- name: "Include OS/WSL Variables"
  ansible.builtin.include_vars: "{{ wsl_version }}/vars-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
  tags: wsl-keeagent

- name: "Run OS/WSL Tasks"
  ansible.builtin.include_tasks: "{{ wsl_version }}/tasks-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
  tags: wsl-keeagent
