---
- name: "Install dependencies"
  become: true
  ansible.builtin.package:
    name: "{{ wsl_keeagent_dependencies }}"
    state: present
  tags: wsl-keeagent

- name: "Get wsl-ssh-agent release info"
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ wsl_keeagent_github_repo }}/releases/{{ 'latest' if wsl_keeagent_version == 'latest' else 'tags/v' + wsl_keeagent_version }}"
    return_content: true
  register: wsl_keeagent_release
  tags: wsl-keeagent

- name: "Set download URL fact"
  ansible.builtin.set_fact:
    wsl_keeagent_download_url: "{{ wsl_keeagent_release.json.assets | map(attribute='browser_download_url') | select('search', '.zip$') | first }}"
  tags: wsl-keeagent

- name: "Download and extract wsl-ssh-agent"
  ansible.builtin.unarchive:
    src: "{{ wsl_keeagent_download_url }}"
    dest: "/tmp"
    remote_src: yes
  tags: wsl-keeagent

- name: "Locate the extracted binary"
  ansible.builtin.find:
    paths: "/tmp"
    patterns: "*.exe"
    recurse: yes
  register: found_exe
  tags: wsl-keeagent

- name: "Fail if no executable was found in ZIP"
  ansible.builtin.fail:
    msg: "The ZIP was extracted, but no .exe was found in /tmp. Run 'ls -R /tmp' to investigate."
  when: found_exe.matched == 0
  tags: wsl-keeagent

- name: "Install Windows binary to Linux path"
  become: true
  ansible.builtin.copy:
    src: "{{ found_exe.files[0].path }}"
    dest: "{{ wsl_keeagent_bin_path }}"
    mode: '0755'
    owner: root
    group: root
    remote_src: true
  tags: wsl-keeagent

- debug: var=ansible_env.HOME
  tags: always

- name: "Ensure user systemd directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: '0755'
  tags: wsl-keeagent

- name: "Deploy Systemd User Service"
  ansible.builtin.template:
    src: "{{ templates_root }}/wsl-ssh-agent.service.j2"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/wsl-ssh-agent.service"
    mode: '0644'
  notify:
    - Reload systemd user
    - Restart wsl-ssh-agent
  tags: wsl-keeagent

- name: "Enable and Start wsl-ssh-agent service"
  ansible.builtin.systemd:
    name: "wsl-ssh-agent"
    scope: user
    enabled: true
    state: started
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_real_user_id }}"
  tags: wsl-keeagent

- name: "Configure SSH_AUTH_SOCK in profile.d"
  become: true
  ansible.builtin.template:
    src: "{{ templates_root }}/wsl-keeagent.sh.j2"
    dest: "/etc/profile.d/wsl-keeagent.sh"
    mode: '0644'
  tags: wsl-keeagent
