---
# handlers file for wsl-keeagent

- name: "Reload systemd"
  ansible.builtin.command: systemctl daemon-reload
  listen: "Reload systemd"
  tags: wsl-keeagent

- name: "Restart wsl-keeagent"
  ansible.builtin.service:
    name: "{{ wsl_keeagent_service_name }}"
    state: restarted
  listen: "Restart wsl-keeagent"
  tags: wsl-keeagent
