---
- name: "Reload systemd user"
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_real_user_id }}"

- name: "Restart wsl-ssh-agent"
  ansible.builtin.systemd:
    name: "wsl-ssh-agent"
    scope: user
    state: restarted
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_real_user_id }}"
